VERZIJA=CDX
MODUL=SII

PRGS=../main/1g/e.prg
CS=
ASMS=

FMK_LIBS=fmk_roba.lib fmk_svi.lib fmk_pi.lib fmk_evn.lib fmk_sec.lib fmk_rab.lib fmk_lok.lib

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc2g_db.lib sc1g_rpt.lib sc2g_cui.lib sc1g_key.lib 

MODUL_LIBS=sii_1db.lib sii_2db.lib sii_1dok.lib sii_1ma.lib sii_2ma.lib sii_1par.lib sii_1rpt.lib sii_1sif.lib 

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
